/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602491;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author W7-JUEGOS
 */
public class EliminarBibliografia extends javax.swing.JFrame {
    public Bibliografia bibliografia;
    /**
     * Creates new form EliminarBibliografia
     */
    public EliminarBibliografia() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTituloEliminarBiblio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAutorEliminarBiblio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDrescripcionEliminarBiblio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPalabraClaveEliminarBiblio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdicionEliminarBiblio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTemasEliminarBiblio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarEliminarBiblio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTipoEliminarBiblio = new javax.swing.JTextField();
        txtFrecuenciaEliminarBiblio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEjemplaresEliminarBiblio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAreaEliminarBiblio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCopiasEliminarBiblio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDisponiblesEliminarBiblio = new javax.swing.JTextField();
        btnEliminarBiblio = new javax.swing.JButton();
        btnCancelarEliminarBiblio = new javax.swing.JButton();

        setTitle("Eliminar ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Eliminar Bibliografia");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Titulo:");

        txtTituloEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Autor:");

        txtAutorEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAutorEliminarBiblio.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion:");

        txtDrescripcionEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDrescripcionEliminarBiblio.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Palabra Clave:");

        txtPalabraClaveEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPalabraClaveEliminarBiblio.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Edicion:");

        txtEdicionEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEdicionEliminarBiblio.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Temas:");

        txtTemasEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTemasEliminarBiblio.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Tipo:");

        btnBuscarEliminarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscarEliminarBiblio.setText("Buscar");
        btnBuscarEliminarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarBiblioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Frecuencia Actual:");

        txtTipoEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoEliminarBiblio.setEnabled(false);

        txtFrecuenciaEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFrecuenciaEliminarBiblio.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Ejemplares:");

        txtEjemplaresEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEjemplaresEliminarBiblio.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Area:");

        txtAreaEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAreaEliminarBiblio.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Copias:");

        txtCopiasEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCopiasEliminarBiblio.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Disponibles:");

        txtDisponiblesEliminarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDisponiblesEliminarBiblio.setEnabled(false);

        btnEliminarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnEliminarBiblio.setText("Eliminar");
        btnEliminarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBiblioActionPerformed(evt);
            }
        });

        btnCancelarEliminarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelarEliminarBiblio.setText("Cancelar");
        btnCancelarEliminarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEliminarBiblioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtAutorEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtTituloEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscarEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTipoEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel8))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtDrescripcionEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtPalabraClaveEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtEdicionEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtTemasEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(83, 83, 83)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDisponiblesEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtCopiasEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtAreaEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtEjemplaresEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(txtFrecuenciaEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnCancelarEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTituloEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAutorEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFrecuenciaEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDrescripcionEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEjemplaresEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalabraClaveEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdicionEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCopiasEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemasEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisponiblesEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEliminarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEliminarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarBiblioActionPerformed
        for(int i=0; i<bibliografia.contadorb; i++){
            if(txtTituloEliminarBiblio.getText().equals("")){
                txtAutorEliminarBiblio.setText("");
                txtDrescripcionEliminarBiblio.setText("");
                txtPalabraClaveEliminarBiblio.setText("");
                txtEdicionEliminarBiblio.setText("");
                txtTemasEliminarBiblio.setText("");
                txtFrecuenciaEliminarBiblio.setText("");
                txtEjemplaresEliminarBiblio.setText("");
                txtAreaEliminarBiblio.setText("");
                txtCopiasEliminarBiblio.setText("");
                txtDisponiblesEliminarBiblio.setText("");
                JOptionPane.showMessageDialog(null, "Ingrese un Titulo para buscar.");
                
            }else if(txtTituloEliminarBiblio.getText().equals(bibliografia.titulo[i])){
                txtAutorEliminarBiblio.setText(bibliografia.autor[i]);
                txtDrescripcionEliminarBiblio.setText(bibliografia.descripcion[i]);
                txtPalabraClaveEliminarBiblio.setText(bibliografia.palabraclave[i]);
                txtEdicionEliminarBiblio.setText(String.valueOf(bibliografia.edicion[i]));
                txtTemasEliminarBiblio.setText(bibliografia.temas[i]);
                txtFrecuenciaEliminarBiblio.setText(bibliografia.frecuencia[i]);
                txtEjemplaresEliminarBiblio.setText(String.valueOf(bibliografia.ejemplares[i]));
                txtAreaEliminarBiblio.setText(bibliografia.area[i]);
                txtCopiasEliminarBiblio.setText(String.valueOf(bibliografia.copias[i]));
                txtDisponiblesEliminarBiblio.setText(String.valueOf(bibliografia.disponibles[i]));
                txtTipoEliminarBiblio.setText(String.valueOf(bibliografia.tipo[i]));
                
            }else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado el Titulo buscado.");
            }
        }
    }//GEN-LAST:event_btnBuscarEliminarBiblioActionPerformed

    private void btnCancelarEliminarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEliminarBiblioActionPerformed
        txtTituloEliminarBiblio.setText("");
        txtAutorEliminarBiblio.setText("");
        txtDrescripcionEliminarBiblio.setText("");
        txtPalabraClaveEliminarBiblio.setText("");
        txtEdicionEliminarBiblio.setText("");
        txtTemasEliminarBiblio.setText("");
        txtFrecuenciaEliminarBiblio.setText("");
        txtEjemplaresEliminarBiblio.setText("");
        txtAreaEliminarBiblio.setText("");
        txtCopiasEliminarBiblio.setText("");
        txtDisponiblesEliminarBiblio.setText("");
    }//GEN-LAST:event_btnCancelarEliminarBiblioActionPerformed

    private void btnEliminarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBiblioActionPerformed
        for(int i=0; i<bibliografia.contadorb; i++){
            if(txtTituloEliminarBiblio.getText().equals(bibliografia.titulo[i])){
                bibliografia.titulo[i]="";
                bibliografia.autor[i]="";
                bibliografia.descripcion[i]="";
                bibliografia.palabraclave[i]="";
                bibliografia.temas[i]="";
                bibliografia.frecuencia[i]="";
                bibliografia.area[i]="";
                bibliografia.edicion[i]=bibliografia.edicion[i]-bibliografia.edicion[i];
                bibliografia.copias[i]=bibliografia.copias[i]-bibliografia.copias[i];
                bibliografia.ejemplares[i]= bibliografia.ejemplares[i]- bibliografia.ejemplares[i];
                bibliografia.disponibles[i]=bibliografia.disponibles[i]-bibliografia.disponibles[i];
                bibliografia.tipo[i]=bibliografia.tipo[i]-bibliografia.tipo[i];
                txtTituloEliminarBiblio.setText("");
                txtAutorEliminarBiblio.setText("");
                txtDrescripcionEliminarBiblio.setText("");
                txtPalabraClaveEliminarBiblio.setText("");
                txtEdicionEliminarBiblio.setText("");
                txtTemasEliminarBiblio.setText("");
                txtFrecuenciaEliminarBiblio.setText("");
                txtEjemplaresEliminarBiblio.setText("");
                txtAreaEliminarBiblio.setText("");
                txtCopiasEliminarBiblio.setText("");
                txtDisponiblesEliminarBiblio.setText("");
                JOptionPane.showMessageDialog(null, "La bibliografia ha sido eliminada.", "Aviso", WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarBiblioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarBibliografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEliminarBiblio;
    private javax.swing.JButton btnCancelarEliminarBiblio;
    private javax.swing.JButton btnEliminarBiblio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAreaEliminarBiblio;
    private javax.swing.JTextField txtAutorEliminarBiblio;
    private javax.swing.JTextField txtCopiasEliminarBiblio;
    private javax.swing.JTextField txtDisponiblesEliminarBiblio;
    private javax.swing.JTextField txtDrescripcionEliminarBiblio;
    private javax.swing.JTextField txtEdicionEliminarBiblio;
    private javax.swing.JTextField txtEjemplaresEliminarBiblio;
    private javax.swing.JTextField txtFrecuenciaEliminarBiblio;
    private javax.swing.JTextField txtPalabraClaveEliminarBiblio;
    private javax.swing.JTextField txtTemasEliminarBiblio;
    private javax.swing.JTextField txtTipoEliminarBiblio;
    private javax.swing.JTextField txtTituloEliminarBiblio;
    // End of variables declaration//GEN-END:variables
}
