/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_201602491;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author W7-JUEGOS
 */
public class ModificarBibliografia extends javax.swing.JFrame {
    public Bibliografia bibliografia;
    /**
     * Creates new form ModificarBibliografia
     */
    public ModificarBibliografia() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTituloModificar = new javax.swing.JTextField();
        btnBuscarModificarBiblio = new javax.swing.JButton();
        comboModificarBiblio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAutorModificar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcionModificar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPalabraClaveModificar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEdicionModificar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFrecuenciaModificar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEjemplaresModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTemasModificar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAreaModificar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCopiasModificar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDisponiblesModificar = new javax.swing.JTextField();
        btnGuardarModificarBiblio = new javax.swing.JButton();
        btnCancelarModificarBiblio = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTipoActualModificarBiblio = new javax.swing.JTextField();

        setTitle("Modificar Biblografia");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Modificar Bibliografia");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");

        txtTituloModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnBuscarModificarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscarModificarBiblio.setText("Buscar");
        btnBuscarModificarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarBiblioActionPerformed(evt);
            }
        });

        comboModificarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboModificarBiblio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Tesis" }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Autor:");

        txtAutorModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Descripcion:");

        txtDescripcionModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Palabra Clave:");

        txtPalabraClaveModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Edicion:");

        txtEdicionModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Frecuencia Actual:");

        txtFrecuenciaModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Ejemplares:");

        txtEjemplaresModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Temas:");

        txtTemasModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Area:");

        txtAreaModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Copias:");

        txtCopiasModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Disponibles:");

        txtDisponiblesModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnGuardarModificarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardarModificarBiblio.setText("Guardar");
        btnGuardarModificarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificarBiblioActionPerformed(evt);
            }
        });

        btnCancelarModificarBiblio.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelarModificarBiblio.setText("Cancelar");
        btnCancelarModificarBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarBiblioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Tipo Actual:");

        txtTipoActualModificarBiblio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTipoActualModificarBiblio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoActualModificarBiblio.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(264, 264, 264)
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTipoActualModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(txtDescripcionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtPalabraClaveModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtEdicionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTemasModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(txtAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtCopiasModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)
                                            .addComponent(txtAreaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtEjemplaresModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtFrecuenciaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(txtDisponiblesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnGuardarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(btnCancelarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(txtTipoActualModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuenciaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEjemplaresModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPalabraClaveModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCopiasModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdicionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisponiblesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemasModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarModificarBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarModificarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarBiblioActionPerformed
        for(int i=0; i<bibliografia.contadorb; i++){
            if(txtTituloModificar.getText().equals("")){
                txtAutorModificar.setText("");
                txtDescripcionModificar.setText("");
                txtPalabraClaveModificar.setText("");
                txtEdicionModificar.setText("");
                txtTemasModificar.setText("");
                txtFrecuenciaModificar.setText("");
                txtEjemplaresModificar.setText("");
                txtAreaModificar.setText("");
                txtCopiasModificar.setText("");
                txtDisponiblesModificar.setText("");
                JOptionPane.showMessageDialog(null, "Ingrese un Titulo para buscar.");
                
            }else if(txtTituloModificar.getText().equals(bibliografia.titulo[i])){
                txtAutorModificar.setText(bibliografia.autor[i]);
                txtDescripcionModificar.setText(bibliografia.descripcion[i]);
                txtPalabraClaveModificar.setText(bibliografia.palabraclave[i]);
                txtEdicionModificar.setText(String.valueOf(bibliografia.edicion[i]));
                txtTemasModificar.setText(bibliografia.temas[i]);
                txtFrecuenciaModificar.setText(bibliografia.frecuencia[i]);
                txtEjemplaresModificar.setText(String.valueOf(bibliografia.ejemplares[i]));
                txtAreaModificar.setText(bibliografia.area[i]);
                txtCopiasModificar.setText(String.valueOf(bibliografia.copias[i]));
                txtDisponiblesModificar.setText(String.valueOf(bibliografia.disponibles[i]));
                txtTipoActualModificarBiblio.setText(String.valueOf(bibliografia.tipo[i]));
                
            }else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado el Titulo buscado.");
            }
        }
    }//GEN-LAST:event_btnBuscarModificarBiblioActionPerformed

    private void btnGuardarModificarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificarBiblioActionPerformed
        for(int i=0; i<bibliografia.contadorb; i++){
            if(txtTituloModificar.getText().equals(bibliografia.titulo[i])){
                try{
                bibliografia.titulo[i]=txtTituloModificar.getText();
                bibliografia.autor[i]=txtAutorModificar.getText();    
                bibliografia.descripcion[i]=txtDescripcionModificar.getText();
                bibliografia.palabraclave[i]=txtPalabraClaveModificar.getText();
                bibliografia.edicion[i]=Integer.valueOf(txtEdicionModificar.getText());
                bibliografia.temas[i]=txtTemasModificar.getText();
                bibliografia.frecuencia[i]=txtFrecuenciaModificar.getText();
                bibliografia.ejemplares[i]=Integer.valueOf(txtEjemplaresModificar.getText());
                bibliografia.area[i]=txtAreaModificar.getText();
                bibliografia.copias[i]=Integer.valueOf(txtCopiasModificar.getText());
                bibliografia.disponibles[i]=Integer.valueOf(txtDisponiblesModificar.getText());
                bibliografia.tipo[i]=comboModificarBiblio.getSelectedIndex();
                txtAutorModificar.setText("");
                txtDescripcionModificar.setText("");
                txtPalabraClaveModificar.setText("");
                txtEdicionModificar.setText("");
                txtTemasModificar.setText("");
                txtFrecuenciaModificar.setText("");
                txtEjemplaresModificar.setText("");
                txtAreaModificar.setText("");
                txtCopiasModificar.setText("");
                txtDisponiblesModificar.setText("");
                JOptionPane.showMessageDialog(null, "La bibliografia ha sido modificada.", "Aviso", WARNING_MESSAGE);
                break;
                }catch(java.lang.NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Ingrese datos validos.");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error!!", "Aviso", WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado la bibliografia.");
            }
        }
    }//GEN-LAST:event_btnGuardarModificarBiblioActionPerformed

    private void btnCancelarModificarBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarBiblioActionPerformed
        txtAutorModificar.setText("");
        txtDescripcionModificar.setText("");
        txtPalabraClaveModificar.setText("");
        txtEdicionModificar.setText("");
        txtTemasModificar.setText("");
        txtFrecuenciaModificar.setText("");
        txtEjemplaresModificar.setText("");
        txtAreaModificar.setText("");
        txtCopiasModificar.setText("");
        txtDisponiblesModificar.setText("");
    }//GEN-LAST:event_btnCancelarModificarBiblioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarBibliografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarModificarBiblio;
    private javax.swing.JButton btnCancelarModificarBiblio;
    private javax.swing.JButton btnGuardarModificarBiblio;
    private javax.swing.JComboBox<String> comboModificarBiblio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAreaModificar;
    private javax.swing.JTextField txtAutorModificar;
    private javax.swing.JTextField txtCopiasModificar;
    private javax.swing.JTextField txtDescripcionModificar;
    private javax.swing.JTextField txtDisponiblesModificar;
    private javax.swing.JTextField txtEdicionModificar;
    private javax.swing.JTextField txtEjemplaresModificar;
    private javax.swing.JTextField txtFrecuenciaModificar;
    private javax.swing.JTextField txtPalabraClaveModificar;
    private javax.swing.JTextField txtTemasModificar;
    private javax.swing.JTextField txtTipoActualModificarBiblio;
    private javax.swing.JTextField txtTituloModificar;
    // End of variables declaration//GEN-END:variables
}
